### ISSUE TITLE
compare plots for rh needed in create_ge_compare_plot_report_lbe

### ISSUE THREAD

**Issue by adributty** [pvrqualitasag/qgert#16]
following the development of lbe for rh with mix99 and the same pattern than for bv and je, the compare plot report for this breed should also be produced with the general function "create_ge_compare_plot_report_lbe".
the function "create_ge_compare_plot_report_lbe_rh" will eventually become obsolete if the Interbull test run of this GE is successful.

**Comment by pvrqualitasag** [comment]
Due to changes since 1908, the comparison plot report for rh does not work yet. Starting from 2004, it is expected to work like the others. The change is effective since version 0.2.5 of qgert.
