### ISSUE TITLE
split_gsRuns_sorted_rt.sh qgert::split_gsruns_sorted_rt() berücksichtigt *.snpBin nicht

### ISSUE THREAD

**Issue by usuqualitasag** [pvrqualitasag/qgert#19]
Für jede GS-Auswertungsrasse wird ein Job verwendet um die Datei mit den SNP-Daten in eine binäre Version zu überführen. Diese Jobs dürfen in den gesplitteten Dateien nicht erscheinen, sonst werden die Analyseergebnisse gelöscht.

**Comment by pvrqualitasag** [comment]
Fixed with release 0.2.8. Remains to be included in unit-tests
