### ISSUE TITLE
create_ge_compare_plot_report_vrdggozw_prov will ge_plot_report_vrdggozw_prov_compare_rh_DGZW.tex 2mal löschen

### ISSUE THREAD

**Issue by adributty** [pvrqualitasag/qgert#20]
Die Funktion "create_ge_compare_plot_report_vrdggozw_prov" sucht nach den oben gennanten .tex file nachdem das File schon gelöscht worden ist und bricht dafür ab.

**Comment by pvrqualitasag** [comment]
Added a check whether the file exists before deleting it. It is not completely clear why this must be done. But it should fix the problem.
