### ISSUE TITLE
Rasse als input Angabe für die Funktionen create_ge_compare_plot_report_vrdggozw und create_ge_compare_plot_report_vrdggozw_prov

### ISSUE THREAD

**Issue by adributty** [pvrqualitasag/qgert#21]
Sollte ein Fehler mit die oben gennanten Funktionnen, wäre ein Restart da wo's das Problem gab sehr praktisch (somit nicht alle Rassen plots wieder neu geloopt sein müssen)
Vorschlag: als input jede rasse einzel (bv, ob, rh, si, sf) oder "alle" eingeben können.

**Comment by pvrqualitasag** [comment]
Das ist möglich, aber mit nicht all zu grossem Aufwand müsste dann für jede Rassen einen separaten Report erzeugt werden. Eine Re-Start-Option mit nur einem Report (alles im gleichen pdf) ist kompliziert.

**Comment by pvrqualitasag** [comment]
Das sollte möglich sein, mit der Rasse als Argument.

**Comment by pvrqualitasag** [comment]
Prinzipiell, das sollte schon möglich sein mit dem Aufruf:
```
create_ge_compare_plot_report_vrdggozw_prov <- function(pn_cur_ge_label = 1912,
                                               pn_prev_ge_label = 1908,
                                               pl_plot_opts = list(ge_dir_stem     = '/qualstorzws01/data_projekte/projekte/calcVRDGGOZW/result',
              arch_dir_stem   = '/qualstorzws01/data_archiv/zws',
              rmd_templ       = system.file('templates/compare_plots.Rmd.template', package = 'qgert'),
              rmd_report_stem = 'ge_plot_report_vrdggozw_prov',
              vec_breed       = c('rh'),
              vec_zw_type     = c('VRZW', 'DGZW', 'GOZW'),
              report_text     = '## Comparison Of Plots\nPlots compare estimates of ZW-type {zwt} for breed {breed} between GE-run {pn_prev_ge_label} on the left and the current GE-run {pn_cur_ge_label} on the right.')))

```
It would be nicer to extract the breed as a single argument and also be able to specify it from the bash script.

**Comment by pvrqualitasag** [comment]
Starting with release 0.2.9 all comparison plot reports can be generated for just one specific breed. To do so the R-functions accept the additional function parameter `ps_breed` and the shell scripts were extended by the command line argument `-b`
